/**
 * Copy dos e-mails transacionais. Cada e-mail é uma lista de blocos (ver
 * build.mjs). Regras: sem oferta ou publicidade (Termos, item 9); linguagem
 * simples, pensada para quem tem 14 a 17 anos; nada de "convidado/a": a
 * pessoa "recebe um convite".
 */
export const emails = [
  {
    file: "01-inscricao-recebida",
    subject: "Recebemos sua inscrição no AUVP Carreiras",
    preheader: "O próximo passo é o Desafio de Potencial. Vamos combinar tudo por e-mail.",
    trigger: "Logo após o envio do formulário da LP.",
    vars: ["nome", "instituicao", "serie_curso", "contato", "acessibilidade_resumo"],
    body: (b, { dpoLink }) => [
      b.check(),
      b.kicker("Inscrição recebida"),
      b.title("Tudo certo, {{nome}}."),
      b.p("Sua inscrição no AUVP Carreiras chegou até a gente. Obrigado por topar o desafio."),
      b.p("<strong style=\"color:#fbfaf9;\">O próximo passo é o Desafio de Potencial.</strong> Ele acontece depois: vamos enviar para este e-mail a data, o horário e como acessar. Não precisa fazer nada agora."),
      b.box(
        [
          ["Instituição", "{{instituicao}}"],
          ["Ano/série ou curso", "{{serie_curso}}"],
          ["Contato", "{{contato}}"],
          ["Acessibilidade", "{{acessibilidade_resumo}}"],
        ],
        "O que você informou",
      ),
      b.note(`Algum dado errado? Responda este e-mail ou escreva para ${dpoLink("#fbfaf9")}.`),
      b.note("Lembrete importante: participar do Desafio é voluntário e não garante convite, vaga ou contratação. Você pode desistir quando quiser."),
      b.divider(),
      b.sign(),
    ],
  },

  {
    file: "02-convite-desafio",
    subject: "Seu Desafio de Potencial está marcado",
    preheader: "{{data_desafio}}, {{horario_desafio}}. Veja como acessar e se preparar.",
    trigger: "Quando a equipe define a data do Desafio para a pessoa inscrita.",
    vars: ["nome", "data_desafio", "horario_desafio", "duracao", "formato", "link_desafio", "prazo_adaptacao"],
    body: (b) => [
      b.kicker("Desafio de Potencial"),
      b.title("{{nome}}, chegou a sua vez."),
      b.p("O Desafio de Potencial é uma atividade voluntária e gratuita para conhecer como você pensa, aprende e resolve problemas. Não existe resposta \"de decoreba\": vale o seu raciocínio."),
      b.box([
        ["Data", "{{data_desafio}}"],
        ["Horário", "{{horario_desafio}}"],
        ["Duração", "{{duracao}}"],
        ["Formato", "{{formato}}"],
      ]),
      b.button("Acessar o Desafio", "{{link_desafio}}"),
      b.p("<strong style=\"color:#fbfaf9;\">Antes de começar</strong>, você vai confirmar que tem 14 anos completos ou mais e que leu as informações sobre o Desafio e o tratamento dos seus dados."),
      b.steps([
        "Separe um tempo sem interrupções e, se for online, uma conexão estável.",
        "Leia cada questão com calma. Algumas são corrigidas automaticamente, mas quem decide os convites é sempre uma pessoa da nossa equipe.",
        "Precisa de alguma adaptação ou recurso de acessibilidade? Responda este e-mail até {{prazo_adaptacao}}. Não é necessário enviar laudo, diagnóstico ou CID.",
      ]),
      b.note("Fazer o Desafio não garante convite, vaga ou contratação. Se não quiser mais participar, é só responder este e-mail."),
      b.divider(),
      b.sign(),
    ],
  },

  {
    file: "03-lembrete-desafio",
    subject: "Lembrete: seu Desafio de Potencial é {{quando}}",
    preheader: "{{data_desafio}}, {{horario_desafio}}. O link de acesso está aqui.",
    trigger: "24 horas (ou outro prazo) antes do Desafio.",
    vars: ["nome", "quando", "data_desafio", "horario_desafio", "formato", "link_desafio"],
    body: (b) => [
      b.kicker("Lembrete"),
      b.title("Seu Desafio é {{quando}}."),
      b.p("Oi, {{nome}}. Passando para lembrar do seu Desafio de Potencial. Deixe este e-mail à mão: o link de acesso está logo abaixo."),
      b.box([
        ["Data", "{{data_desafio}}"],
        ["Horário", "{{horario_desafio}}"],
        ["Formato", "{{formato}}"],
      ]),
      b.button("Acessar o Desafio", "{{link_desafio}}"),
      b.note("Não vai conseguir participar ou precisa de alguma adaptação? Responda este e-mail. Não é necessário enviar laudo, diagnóstico ou CID."),
      b.divider(),
      b.sign(),
    ],
  },

  {
    file: "04-adaptacao-confirmada",
    subject: "Sua adaptação para o Desafio está confirmada",
    preheader: "Preparamos o recurso que você pediu. Veja como vai funcionar.",
    trigger: "Quando a equipe confirma o recurso de acessibilidade pedido no formulário ou por e-mail.",
    vars: ["nome", "recurso", "como_funciona", "data_desafio"],
    body: (b) => [
      b.check(),
      b.kicker("Acessibilidade"),
      b.title("Adaptação confirmada, {{nome}}."),
      b.p("Recebemos o seu pedido e preparamos tudo para que você faça o Desafio de Potencial em igualdade de condições."),
      b.box([
        ["Recurso", "{{recurso}}"],
        ["Como vai funcionar", "{{como_funciona}}"],
        ["Data do Desafio", "{{data_desafio}}"],
      ]),
      b.p("Essa informação é usada apenas para oferecer a adaptação e não entra na sua avaliação."),
      b.note("Se precisar de algo diferente, é só responder este e-mail."),
      b.divider(),
      b.sign(),
    ],
  },

  {
    file: "05-desafio-concluido",
    subject: "Recebemos suas respostas do Desafio de Potencial",
    preheader: "Agora é com a gente. Você recebe um retorno até {{prazo_retorno}}.",
    trigger: "Quando a pessoa termina o Desafio.",
    vars: ["nome", "prazo_retorno"],
    body: (b) => [
      b.check(),
      b.kicker("Desafio concluído"),
      b.title("Missão cumprida, {{nome}}."),
      b.p("Suas respostas do Desafio de Potencial foram recebidas. Obrigado pelo tempo e pela dedicação."),
      b.p("<strong style=\"color:#fbfaf9;\">E agora?</strong>"),
      b.steps([
        "Algumas questões são corrigidas automaticamente e geram sua pontuação.",
        "Uma pessoa da nossa equipe analisa os resultados. A decisão sobre quem recebe convite para a próxima etapa nunca é só da máquina.",
        "Você recebe um retorno por e-mail até {{prazo_retorno}}.",
      ]),
      b.note("A pontuação sozinha não garante convite, vaga ou contratação: os convites dependem dos critérios do programa e das oportunidades abertas."),
      b.divider(),
      b.sign(),
    ],
  },

  {
    file: "06-convite-proxima-etapa",
    subject: "Você recebeu um convite para a próxima etapa do AUVP Carreiras",
    preheader: "Seu desempenho chamou a nossa atenção. Confirme sua participação.",
    trigger: "Após a revisão humana, para participantes com 18 anos ou mais.",
    vars: ["nome", "etapa", "data_etapa", "formato", "link_confirmacao", "prazo_confirmacao"],
    body: (b) => [
      b.kicker("Próxima etapa"),
      b.title("{{nome}}, queremos te conhecer melhor."),
      b.p("Depois de analisar o seu Desafio de Potencial, a nossa equipe quer seguir com você para a próxima etapa do AUVP Carreiras."),
      b.box([
        ["Etapa", "{{etapa}}"],
        ["Quando", "{{data_etapa}}"],
        ["Formato", "{{formato}}"],
        ["Confirme até", "{{prazo_confirmacao}}"],
      ]),
      b.button("Confirmar participação", "{{link_confirmacao}}"),
      b.note("O convite é para conhecer uma oportunidade ou participar de um processo seletivo. Ele não é uma contratação e não garante vaga."),
      b.divider(),
      b.sign(),
    ],
  },

  {
    file: "07-convite-proxima-etapa-menor",
    subject: "Você recebeu um convite para a próxima etapa do AUVP Carreiras",
    preheader: "Para seguir, precisamos da autorização do seu responsável legal.",
    trigger: "Após a revisão humana, para participantes de 14 a 17 anos.",
    vars: ["nome", "etapa", "data_etapa", "link_autorizacao", "prazo_autorizacao"],
    body: (b) => [
      b.kicker("Próxima etapa"),
      b.title("{{nome}}, queremos te conhecer melhor."),
      b.p("Depois de analisar o seu Desafio de Potencial, a nossa equipe quer seguir com você para a próxima etapa do AUVP Carreiras."),
      b.box([
        ["Etapa", "{{etapa}}"],
        ["Quando", "{{data_etapa}}"],
        ["Autorização até", "{{prazo_autorizacao}}"],
      ]),
      b.p("<strong style=\"color:#fbfaf9;\">Como você tem menos de 18 anos, precisamos da autorização do seu responsável legal para seguir.</strong> É simples:"),
      b.steps([
        "Mostre este e-mail para o seu responsável legal (mãe, pai ou quem tem a sua guarda).",
        "Juntos, abram o Termo de Autorização pelo botão abaixo. Ele explica a próxima etapa e como seus dados serão usados.",
        "O seu responsável preenche e assina até {{prazo_autorizacao}}. Nós avisamos você assim que recebermos.",
      ]),
      b.button("Abrir Termo de Autorização", "{{link_autorizacao}}"),
      b.note("Sem a autorização, não é possível avançar para as atividades que dependem dela. O convite não é uma contratação e não garante vaga."),
      b.divider(),
      b.sign(),
    ],
  },

  {
    file: "08-autorizacao-responsavel",
    subject: "Pedido de autorização: {{nome_participante}} no AUVP Carreiras",
    preheader: "{{nome_participante}} recebeu um convite para a próxima etapa. Sua autorização é necessária.",
    trigger: "Enviado ao responsável legal, quando o e-mail dele é informado no Termo de Autorização.",
    vars: ["nome_responsavel", "nome_participante", "etapa", "data_etapa", "link_autorizacao", "prazo_autorizacao"],
    reason: "Você recebeu este e-mail porque foi indicado como responsável legal de uma pessoa inscrita no AUVP Carreiras.",
    tag: "Para o responsável legal",
    body: (b, { link, LINKS }) => [
      b.kicker("Autorização do responsável"),
      b.title("Olá, {{nome_responsavel}}."),
      b.p("{{nome_participante}} participou do Desafio de Potencial, uma atividade voluntária e gratuita do AUVP Carreiras, programa da HOLDING SUPERNOVA LTDA (grupo AUVP) para conhecer e desenvolver jovens de 14 a 21 anos."),
      b.p("Depois da análise da nossa equipe, {{nome_participante}} recebeu um convite para a próxima etapa. Como é menor de 18 anos, a participação depende da sua ciência e autorização."),
      b.box([
        ["Etapa", "{{etapa}}"],
        ["Quando", "{{data_etapa}}"],
        ["Prazo para autorizar", "{{prazo_autorizacao}}"],
      ]),
      b.button("Ler e autorizar", "{{link_autorizacao}}"),
      b.p(`Até aqui, usamos apenas nome, data de nascimento, instituição de ensino, ano/série ou curso, contato e as respostas do Desafio. Não pedimos CPF, endereço, renda ou dados bancários. Tudo está explicado no ${link(LINKS.privacy, "Aviso de Privacidade")} e nos ${link(LINKS.terms, "Termos de Participação")}.`),
      b.note("O convite não é uma contratação e não garante vaga. Se preferir não autorizar, basta ignorar este e-mail ou nos avisar: não há nenhuma penalidade."),
      b.divider(),
      b.sign(),
    ],
  },

  {
    file: "09-autorizacao-confirmada",
    subject: "Autorização recebida: você segue no AUVP Carreiras",
    preheader: "Seu responsável autorizou. Veja o que vem a seguir.",
    trigger: "Quando o Termo de Autorização assinado é recebido.",
    vars: ["nome", "etapa", "data_etapa", "proximos_passos"],
    body: (b) => [
      b.check(),
      b.kicker("Autorização recebida"),
      b.title("Tudo pronto, {{nome}}."),
      b.p("Recebemos a autorização do seu responsável legal. Você segue para a próxima etapa do AUVP Carreiras."),
      b.box([
        ["Etapa", "{{etapa}}"],
        ["Quando", "{{data_etapa}}"],
        ["O que fazer", "{{proximos_passos}}"],
      ]),
      b.note("Dúvidas? É só responder este e-mail."),
      b.divider(),
      b.sign(),
    ],
  },

  {
    file: "10-nao-selecionado",
    subject: "Sobre a sua participação no AUVP Carreiras",
    preheader: "Obrigado por fazer o Desafio de Potencial. Veja o que acontece com seus dados.",
    trigger: "Após a revisão humana, para quem não segue para a próxima etapa.",
    vars: ["nome", "data_eliminacao"],
    body: (b, { dpoLink }) => [
      b.kicker("Resultado"),
      b.title("Obrigado, {{nome}}."),
      b.p("Queremos agradecer pelo seu tempo e pela sua dedicação no Desafio de Potencial."),
      b.p("Desta vez, não vamos seguir com a sua participação na próxima etapa do AUVP Carreiras. Essa decisão foi revisada por uma pessoa da nossa equipe e considera os critérios do programa e as oportunidades abertas agora. Ela não mede o seu valor nem o seu futuro."),
      b.box(
        [
          ["Até quando", "{{data_eliminacao}} (no máximo 12 meses)"],
          ["Depois disso", "Seus dados são eliminados"],
          ["Uso", "Nunca para publicidade ou ofertas"],
        ],
        "O que acontece com seus dados",
      ),
      b.p(`Você pode pedir a <strong style="color:#fbfaf9;">revisão desta decisão</strong> ou a <strong style="color:#fbfaf9;">exclusão dos seus dados agora</strong> pelo e-mail ${dpoLink("#fbfaf9")}.`),
      b.divider(),
      b.p("Continue estudando e se desafiando. Foi muito bom ter você por aqui."),
      b.sign(),
    ],
  },

  {
    file: "11-direitos-pedido-recebido",
    subject: "Recebemos seu pedido sobre seus dados · protocolo {{protocolo}}",
    preheader: "Vamos responder em até 15 dias.",
    trigger: "Quando chega um pedido de acesso, correção, exclusão, desistência ou revisão de decisão.",
    vars: ["nome", "protocolo", "tipo_pedido", "data_pedido", "prazo_resposta"],
    tag: "Seus dados",
    reason: "Você recebeu este e-mail porque fez um pedido sobre os seus dados no AUVP Carreiras.",
    body: (b) => [
      b.kicker("Pedido recebido"),
      b.title("Estamos cuidando disso, {{nome}}."),
      b.p("Recebemos o seu pedido sobre os dados pessoais que você informou no AUVP Carreiras."),
      b.box([
        ["Protocolo", "{{protocolo}}"],
        ["Pedido", "{{tipo_pedido}}"],
        ["Recebido em", "{{data_pedido}}"],
        ["Resposta até", "{{prazo_resposta}}"],
      ]),
      b.p("Para proteger seus dados, só respondemos para o contato que você informou na inscrição. Se precisarmos confirmar alguma informação, vamos perguntar por aqui. Nunca pedimos senha, CPF ou dados bancários."),
      b.note("Se você tem menos de 18 anos, seu responsável legal também pode acompanhar ou fazer o pedido em seu nome."),
      b.divider(),
      b.sign(),
    ],
  },

  {
    file: "12-direitos-pedido-concluido",
    subject: "Seu pedido sobre seus dados foi concluído · protocolo {{protocolo}}",
    preheader: "{{resumo_resultado}}",
    trigger: "Quando o pedido de direitos é atendido (use {{resultado}} para detalhar: dados enviados, corrigidos, apagados ou decisão revisada).",
    vars: ["nome", "protocolo", "tipo_pedido", "data_conclusao", "resumo_resultado", "resultado"],
    tag: "Seus dados",
    reason: "Você recebeu este e-mail porque fez um pedido sobre os seus dados no AUVP Carreiras.",
    body: (b, { dpoLink }) => [
      b.check(),
      b.kicker("Pedido concluído"),
      b.title("Pronto, {{nome}}."),
      b.p("Atendemos o seu pedido sobre os seus dados no AUVP Carreiras."),
      b.box([
        ["Protocolo", "{{protocolo}}"],
        ["Pedido", "{{tipo_pedido}}"],
        ["Concluído em", "{{data_conclusao}}"],
      ]),
      b.p("{{resultado}}"),
      b.note(`Se os seus dados foram apagados, este é o último e-mail que você recebe do AUVP Carreiras. Discorda do resultado? Escreva para ${dpoLink("#fbfaf9")}. Você também pode procurar a Autoridade Nacional de Proteção de Dados (ANPD).`),
      b.divider(),
      b.sign(),
    ],
  },
];
